[versions]
kotlin = "2.4.0"
agp = "9.3.0"
coroutines = "1.10.2"
detekt = "1.23.8"
ktfmt-gradle = "0.26.0"
kover = "0.9.9"
binary-compatibility-validator = "0.18.1"
dokka = "2.2.0"
skie = "0.10.13"
compose-multiplatform = "1.11.1"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-multiplatform" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt-gradle" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
